/*

 FIXEDBROKENCHARS.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 2 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 6

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0x26,0x49,0x49,0x32,0x00,0x00,0x00,0x00, //S
  0x7F,0x05,0x05,0x02,0x00,0x00,0x00,0x00, //P
  0x3E,0x09,0x09,0x3E,0x00,0x00,0x00,0x00, // A
  0x31,0x29,0x2D,0x25,0x23,0x00,0x00,0x00, // 'Z'
  0x36,0x36,0x00,0x00,0x00,0x00,0x00,0x00, // ':'
};

/* End of FIXEDBROKENCHARS.C */
